# Data Cleaner CronJob
apiVersion: batch/v1
kind: CronJob
metadata:
  name: old-invoices-cleaner
spec:
  schedule: '0 0 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: old-invoices-cleaner
            image: data-cleaner-image
            resources:
              requests:
                memory: '500Mi'
                cpu: '500m'
              limits:
                memory: '1Gi'
                cpu: '1'
          restartPolicy: OnFailure